name: story_teller
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/

